language: python
matrix:
  include:
    - python: "2.7.10"
    - python: "2.7.11"
# command to install dependencies
install: 
  - pip install python-dateutil pytest
# command to run tests
script: py.test -v

